name: test

on:
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: add env
        working-directory: ./www
        run: echo "MONGODB_URI=${{ secrets.MONGODB_URI }}\n" >> .env.local
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./www
          build: npm run build
          start: npm start
